const data = {
    products: [
        {
            _id: '1',
            name: 'Lace Gown',
            category: 'Dress',
            // image: './images/p1.jpg',
            image: '../images/p1.jpg',
            price: 120,
            countInStock: 10,
            brand: 'Deola',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Ankara dress',
            category: 'Dress',
            // image: './images/p2.jpg',
            image: '../images/p2.jpg',
            price: 100,
            countInStock: 20,
            brand: 'Segoe',
            rating: 4.0,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Exotic gown',
            category: 'Dress',
            // image: './images/p3.jpg',
            image: '../images/p3.jpg',
            price: 250,
            countInStock: 15,
            brand: 'Deola',
            rating: 4.9,
            numReviews: 7,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Iro ati buba',
            category: 'two-piece',
            // image: './images/p4.jpg',
            image: '../images/p4.jpg',
            price: 150,
            countInStock: 5,
            brand: 'Segoe',
            rating: 5.0,
            numReviews: 14,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Skirt and blouse',
            category: 'two-piece',
            // image: './images/p5.jpg',
            image: '../images/p5.jpg',
            price: 140,
            countInStock: 12,
            brand: 'Segoe',
            rating: 4.1,
            numReviews: 8,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'English Formalwear',
            category: 'two-piece',
            // image: './images/p6.jpg',
            image: '../images/p6.jpg',
            price: 120,
            countInStock: 0,
            brand: 'Deola',
            rating: 3.3,
            numReviews: 16,
            description: 'high quality product',
        },
    ],
};

export default data;